from .agent_console_controller import AgentAdminRouter, AgentConsoleRouter
from .controller import AiCallRouter
from .follow_up_data_controller import FollowUpDataRouter
from .knowledge_controller import KnowledgePromptRouter, KnowledgeRouter
from .outbound import OutboundValidationRouter
from .runtime_control_controller import RuntimeEntryRouter
from .statistics_controller import OutboundStatisticsRouter
from .voice import VoiceRouter

AiCallRouter.include_router(AgentConsoleRouter)
AiCallRouter.include_router(AgentAdminRouter)
AiCallRouter.include_router(FollowUpDataRouter)
AiCallRouter.include_router(KnowledgeRouter)
AiCallRouter.include_router(KnowledgePromptRouter)
AiCallRouter.include_router(OutboundValidationRouter)
AiCallRouter.include_router(RuntimeEntryRouter)
AiCallRouter.include_router(OutboundStatisticsRouter)
AiCallRouter.include_router(VoiceRouter)

__all__ = ["AiCallRouter"]
