"""发信附件预算与收信读取上限分别维护，避免放开发信影响收信策略。"""

MAX_ATTACHMENT_COUNT = 5
MAX_ATTACHMENT_BYTES = 15 * 1024 * 1024
MAX_OUTBOUND_MESSAGE_BYTES = 25 * 1024 * 1024
MAX_INBOUND_MESSAGE_BYTES = 16 * 1024 * 1024
MAX_INBOUND_ATTACHMENT_BYTES = 8 * 1024 * 1024

ATTACHMENT_ERROR_CODES = {
    'ATTACHMENT_COUNT_LIMIT', 'ATTACHMENT_DUPLICATE', 'ATTACHMENT_TOO_LARGE',
    'ATTACHMENT_TOTAL_TOO_LARGE', 'ATTACHMENT_EMPTY', 'ATTACHMENT_NAME_TOO_LONG',
    'ATTACHMENT_TYPE_UNSUPPORTED', 'ATTACHMENT_INVALID', 'ATTACHMENT_CHANGED',
}
